Name: meego-rpm-config
Summary: MeeGo specific rpm configuration files
Version: 0.18
Release: 1
Group: Development/System
License: GPL+
URL: http://meego.com
Sources:
    - meego-rpm-config-%{version}.tar.bz2
Patches:
    - meego-rpm-config-0.18-merchanges.patch
    - meego-rpm-config-0.18-bashism.patch
    - meego-rpm-config-0.18-flexible-install.patch
    - meego-rpm-config-xzdebuginfo.patch
    - meego-rpm-config-0.18-wnopsabi.patch
Macros:
    - disable_docs_package;1
Description: MeeGo specific rpm configuration files.
BuildArch: noarch
Builder: none
Configure: none
